
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  llm:
    build: .
    container_name: llm
    depends_on:
      - elasticsearch
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8888:8888"
    links:
      - elasticsearch
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]

volumes:
  esdata: